apiVersion: apps/v1
kind: Deployment
metadata:
  name: address-book-deployment
  labels:
    app: address-book
spec:
  replicas: 3
  selector:
    matchLabels:
      app: address-book
  template:
    metadata:
      labels:
        app: address-book
    spec:
      containers:
        - name: address-book
          image: supriyo12345/address-book:v1
          ports:
            - containerPort: 80
